# Generated by Django 5.2.6 on 2025-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movie',
            name='unique_title_year',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_title_179e04_idx',
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'title_en'], name='movies_title_14dd4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'title_en', 'year'), name='unique_title_year'),
        ),
    ]
